# 파이토치 기초문법

### 텐서 생성 및 변환
    - 텐서는 numpy의 ndarray와 비슷하며 GPU에서의 연산도 가능

In [2]:
import torch
print(torch.tensor([[1, 2], [3, 4]]))   #2차원 행태의 텐서
#print(torch.tensor([[1, 2], [3, 4]], device="cuda:0"))   #GPU에 텐서 생성  ==> GPU가 있어야지만 가능
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64))  #dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
tmp = torch.tensor([[1, 2], [3, 4]])
print(tmp.numpy())
'''
tmp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
print(tmp.to("cpu").numpy())
'''

[[1 2]
 [3 4]]


'\ntmp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")\nprint(tmp.to("cpu").numpy())\n'