# 파이토치 기초문법

### 텐서 생성 및 변환
    - 텐서는 numpy의 ndarray와 비슷하며 GPU에서의 연산도 가능

In [2]:
import torch
print(torch.tensor([[1, 2], [3, 4]]))   #2차원 행태의 텐서
#print(torch.tensor([[1, 2], [3, 4]], device="cuda:0"))   #GPU에 텐서 생성  ==> GPU가 있어야지만 가능
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64))  #dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
tmp = torch.tensor([[1, 2], [3, 4]])
print(tmp.numpy())
'''
tmp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
print(tmp.to("cpu").numpy())
'''

[[1 2]
 [3 4]]


'\ntmp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")\nprint(tmp.to("cpu").numpy())\n'

### 텐서의 인덱스 조작

In [6]:
tmp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])   #1차원 벡터
print(tmp[0], tmp[1], tmp[-1])
print("------------------------")
print(tmp[2:5], tmp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


### 텐서 연산 및 차원 조작

- 벡터 두개를 생성하여 사칙연산이 가능

In [8]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [ ]:
tmp = torch.tensor([
    [1, 2], [3, 4]
])

print(tmp.shape)
print("--------------------")
print(tmp.view(4, 1))   #2x2행렬을 4x1로 변형
print("--------------------")
print(tmp.view(-1))   #2x2행렬을 1차원벡터로 변형
print("--------------------")
print(tmp.view(1, -1))   #-1은 (1, ?)와 같은의미로 사용(원소의 개수는 변하지 않음)
print("--------------------")
print(tmp.view(-1, 1))   #(?, 1)